### PR TITLE
Add slotted pseudo class to selector-pseudo-class-no-unknown

### PR DESCRIPTION
**Pull request by segevfiner**
See here for docs https://vuejs.org/api/sfc-css-features.html#slotted-selectors

### CODE REVIEW

**Comment by ota-meshi** [comment]
Duplicate of #15

**Comment by segevfiner** [comment]
So why am I getting an error about it?

**Comment by rogatty** [comment]
@ota-meshi I believe the situation changed since #15. See https://github.com/stylelint/stylelint/pull/6964 which was released in stylelint 15.10.0. After upgrading, I'm seeing the errors too.

**Comment by ota-meshi** [comment]
@rogatty Thanks for letting me know. I didn't know that.

**Comment by rogatty** [comment]
Fixed in https://github.com/ota-meshi/stylelint-config-recommended-vue/pull/52 and released as https://github.com/ota-meshi/stylelint-config-recommended-vue/releases/tag/v1.5.0

**Pull request closed without merging**
